### PR TITLE
Change storage_service.redirect.disabled in harbor.yml.tmpl to storage_service.redirect.deactivate

### PR DESCRIPTION
**Pull request by balonik**
Signed-off-by: balonik <balonik32@gmail.com>

In [docs](https://goharbor.io/docs/2.2.0/install-config/configure-yml-file/) and even in the file itself you mention `disable`, but the property itself is called `disabled`.

This PR changes `disabled` to `disable` property in `harbor.yml.tmpl` and `configs.py` to be inline with the docs.

### CODE REVIEW

**Comment by balonik** [comment]
Just found out that it is `disabled` in `configs.py` as well and changed it.

**Comment by balonik** [comment]
I leave the decision up to maintainers, but either the code or docs need to be fixed.

**Review by ninjadq — APPROVED** [review]
lgtm

**Review by wy65701436 — APPROVED** [review]
lgtm

**Comment by ninjadq** [comment]
hi @balonik could you please update your DCO and squash these two commits

**Comment by balonik** [comment]
Hi @ninjadq should be fine now.

**Comment by wy65701436** [comment]
@balonik could you help to rebase with latest? Once CI is done, I'll merge it.

**Comment by qnetter** [comment]
In line with the inclusive language changes, shouldn't disable be deactivate?

**Comment by wy65701436** [comment]
@balonik per @qnetter 's comment, we should use the deactivate? Can you please help to revise this PR? cc @MinerYang

**Comment by balonik** [comment]
rebased and changed to `deactivate`. I am only changing in harbor config, not touching other internals where `disabled` is used.

**Comment by MinerYang** [comment]
Hi @balonik,

Thanks for your contribution. It seems like if we change the `disabled` into `deactivate`, we not only need to change the `configs.py` file, but also have to care about this configuration in migration jinja file,  otherwise there would be a problem we we running the prerare image for migration.
https://github.com/goharbor/harbor/blob/0559ce7e28553e5145c03eca655f033a417c173d/make/photon/prepare/migrations/version_2_6_0/harbor.yml.jinja#L108

**Comment by MinerYang** [comment]
Hi @balonik ,

I think the `deactivate` option we are setting should consistent with docker registry configuartion https://docs.docker.com/registry/configuration/#list-of-configuration-options. Actually we may intend to using `disable` at very beginning, but typo as `disabled`. So how about we change it into `disable` instead of `disabled` ? 

And I will take charge of the migration jinja file part, no worries for you.

If you are still interested in working on this PR, let's work it out.

**Comment by balonik** [comment]
@MinerYang I have changed it back to `disable` including the Jinja template.

**Comment by MinerYang** [comment]
> @MinerYang I have changed it back to `disable` including the Jinja template.

Sorry for a delay in getting the reply. And here's some incorrect parts in your latest commit, especially in `harbor.yml.jinja` which would affect the script migrating process with errors like below when your previous harbor.yml file is using the `storage_service.redirect.disabled`
```
File "/usr/src/app/migrations/version_2_6_0/harbor.yml.jinja", line 182, in top-level template code
    # for production operations. If, for any reason, it's not enough, you could increase the rate limit to 5000
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'disable'
```
I have just raised a [`sample-pr`](https://github.com/MinerYang/harbor/pull/3) that you can compare and refer to.
If you are still interested in working on this PR, you could submit another one for 2.7 or rebase this one for release-2.6.0 since the version 2.6 has already been released and the main branch is now working on 2.7

**Comment by balonik** [comment]
@MinerYang apologies for the delay on my side and big thanks for the sample PR you have provided. I have updated it for 2.7 release, hopefully now it is all good.

**Comment by MinerYang** [comment]
Hi @balonik ,
Thanks for keep working on this PR. But since we are on the process of new release(harbor 2.8), could you open a new PR for the `main` branch after we have a new `migrations/version_2_8_0` jinja file? But for now, we still on the 2.8 feature dev stage, so this directory has not been created yet.

**Comment by MinerYang** [comment]
I don't think harbor-helm and harbor-operator would not be affected by this PR since helm is using name `disableredirect` and operator side using name `Disable` for the same registry storage redirect configuration, this one only change from the offline installer side
https://github.com/goharbor/harbor-helm/blob/986d9b546d3e2adad2f75c9a8a77f14a31174012/values.yaml#L276
https://github.com/goharbor/harbor-operator/blob/9c19b151ff71f66f9079236e4dc4ce3d4a1e02c3/config/config/assets/registry-config.yaml.tmpl#L85

**Comment by OrlinVasilev** [comment]
@balonik congrats on merging your first PR here :)) Welcome to the club :) even after so much time :)
