### ISSUE TITLE
Update Docs for importing the Clair vulnerability data

### ISSUE THREAD

**Issue by anasypany** [goharbor/harbor#6714]
The docs at https://github.com/goharbor/harbor/blob/master/docs/import_vulnerability_data.md are out of date (they were written for harbor v1.2) and do not work with Harbor v1.7+. The docs still reference the separate Clair-db container that was used before the database consolidation work done in v1.6. 

If anyone has done a vulnerability data migration to an offline install in v1.7+ feel free to share your steps and I will gladly write up a PR for the current docs.

**Comment by SDBrett** [comment]
Self assign

**Comment by reasonerjt** [comment]
@SDBrett I don't think the issue can be assigned to a user that is not a member of `goharbor` team, but please feel free to write up a PR.  
You help will be appreciated!

**Comment by anasypany** [comment]
@SDBrett If you've been able to successfully migrate on v1.7 would you mind sharing the commands you're exporting/importing the data with?

**Comment by SDBrett** [comment]
@anasypany Below are the changes in commands. Pretty much it's all the same, but 'clair-db' is replaced with 'harbor-db'

## Harbor version >= 1.6

Databased were consolidated in version 1.6 which moved the clair database to the harbor-db container and removed the clair-db container.

### Dumping vulnerability data 

- Log in to the host (that is connected to Internet) where Clair database (Postgres) is running.
- Dump Clair's vulnerability database by the following commands, two files (`vulnerability.sql` and `clear.sql`) are generated:

_NOTE: The container name 'clair-db' is a placeholder for the db container used by the internet connected instance of clair_

```
  $ docker exec clair-db /bin/sh -c  "pg_dump -U postgres -a -t feature -t keyvalue -t namespace -t schema_migrations -t vulnerability -t vulnerability_fixedin_feature" > vulnerability.sql
  $ docker exec clair-db /bin/sh -c "pg_dump -U postgres -c -s" > clear.sql
```

### Back up Harbor's Clair database
Before importing the data, it is strongly recommended to back up the Clair database in Harbor.
```
 $ docker exec harbor-db /bin/sh -c  "pg_dump -U postgres -c" > all.sql
```

### Update Harbor's Clair database
Copy the `vulnerability.sql` and `clear.sql` to the host where Harbor is running on. Run the below commands to import the data to Harbor's Clair database:

```
 $ docker exec -i harbor-db psql -U postgres < clear.sql
 $ docker exec -i harbor-db psql -U postgres < vulnerability.sql
```

### Rescanning images
After importing the data, trigger the scanning process in the administrator's web UI: **Administration**->**Configuration**->**Vulnerability**->**SCAN NOW**. Harbor reflects the new changes after the scanning is completed. (Otherwise the summary of the image vulnerabilities will not be displayed correctly.)

**Comment by reasonerjt** [comment]
Closing as #6721 has been merged.

**Comment by haisum** [comment]
These instructions are still invalid. Instead of referring to harbor-db, they refer to clair-db and the dump that they create in vulnerability.sql is only DDLs without any data.
