### ISSUE TITLE
nja2.exceptions.UndefinedError: 'str object' has no attribute 'port' when upgrading to 1.9.0

### ISSUE THREAD

**Issue by joernott** [goharbor/harbor#9296]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Running
```
docker run -it --rm -v /root/harbor/harbor.yml:/harbor-migration/harbor-cfg/harbor.yml goharbor/harbor-migrator:v1.9.0 --cfg up
```
to upgrade from 1.8.0 configuration to 1.9.0 configuration should workl without error.

**Steps to reproduce the problem:**
Having a valid .cfg file for 1.7.0 or a valid yaml-fiel for 1.8.0, I have run the respective upgrade container as specified in [the upgrade and migration docs](https://github.com/goharbor/harbor/blob/master/docs/migration_guide.md).

**Versions:**
- harbor version: [1.9.1-rc1]
- docker engine version: [ce 19.03.1] 
- docker-compose version: [1.23.2]

**Additional context:**

I am getting the following python error message in both cases:
```
Traceback (most recent call last):
  File "./cfg/run.py", line 70, in <module>
    main()
  File "./cfg/run.py", line 46, in main
    m.migrate(curr_input_path, curr_output_path)
  File "/harbor-migration/cfg/migrator_1_9_0/__init__.py", line 21, in migrate
    f.write(tpl.render(**config_dict))
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/harbor-migration/cfg/migrator_1_9_0/harbor.yml.jinja", line 11, in top-level template code
    port: {{ http.port }}
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'port'
```

**Comment by efynn** [comment]
The reason for this problem is that there is no space after the colon when `port: 23658` is configured in harbor.yml
