### ISSUE TITLE
Harbor build fails when building portal container

### ISSUE THREAD

**Issue by prahaladdarkin** [goharbor/harbor#12461]
After merging the latest source code with my fork, I am observing build failures when attempting to build the harbor portal.

To build the source code I am following the instructions on https://goharbor.io/docs/2.0.0/build-customize-contribute/compile-guide/

**Expected behavior and actual behavior:**
The build should complete successfully

**Steps to reproduce the problem:**
* Fetch latest code from remote Harbor upstream
* Merge upstream into the forked branch
**Versions:**
Please specify the versions of following systems.

- harbor version: [2.x]
- docker engine version: [18.09.7]
- docker-compose version: [1.26.2]

**Additional context:**
The build error excerpt are shown below:
```ERROR in app/distribution/distribution-setup-modal/distribution-setup-modal.component.ts:122:48 - error TS2345: Argument of type '{ instanceId: number; propertySet: Instance; }' is not assignable to parameter of type 'UpdateInstanceParams'.
  Object literal may only specify known properties, and 'instanceId' does not exist in type 'UpdateInstanceParams'.

122       this.distributionService.UpdateInstance({instanceId: this.model.id, propertySet: data
                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
app/distribution/distribution-instances/distribution-instances.component.ts:172:11 - error TS2345: Argument of type '{ propertySet: { default: boolean; }; instanceId: number; }' is not assignable to parameter of type 'UpdateInstanceParams'.
  Object literal may only specify known properties, and 'instanceId' does not exist in type 'UpdateInstanceParams'.

172           instanceId: this.selectedRow[0].id
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app/distribution/distribution-instances/distribution-instances.component.ts:276:44 - error TS2345: Argument of type '{ instanceId: number; }' is not assignable to parameter of type 'DeleteInstanceParams'.
  Object literal may only specify known properties, and 'instanceId' does not exist in type 'DeleteInstanceParams'.

276     return this.disService.DeleteInstance({instanceId: instance.id}).pipe(
                                               ~~~~~~~~~~~~~~~~~~~~~~~
app/distribution/distribution-instances/distribution-instances.component.ts:308:9 - error TS2345: Argument of type '{ propertySet: { enabled: boolean; }; instanceId: number; }' is not assignable to parameter of type 'UpdateInstanceParams'.
  Object literal may only specify known properties, and 'instanceId' does not exist in type 'UpdateInstanceParams'.

308         instanceId: instance.id
            ~~~~~~~~~~~~~~~~~~~~~~~
app/distribution/distribution-instances/distribution-instances.component.ts:342:9 - error TS2345: Argument of type '{ propertySet: { enabled: boolean; }; instanceId: number; }' is not assignable to parameter of type 'UpdateInstanceParams'.
  Object literal may only specify known properties, and 'instanceId' does not exist in type 'UpdateInstanceParams'.

342         instanceId: instance.id
            ~~~~~~~~~~~~~~~~~~~~~~~

The command '/bin/sh -c node --max_old_space_size=2048 'node_modules/@angular/cli/bin/ng' build --prod' returned a non-zero code: 1
/home/harbordev/go/src/github.com/goharbor/harbor/make/photon/Makefile:116: recipe for target '_build_portal' failed
make[1]: *** [_build_portal] Error 1
make[1]: Leaving directory '/home/harbordev/go/src/github.com/goharbor/harbor'
Makefile:372: recipe for target 'build' failed
make: *** [build] Error 2```

**Comment by AllForNothing** [comment]
@prahaladdarkin 
Thanks!
This has been fixed by #12459.
